
export type QuotationStateType = {
  CompanyID :string;
  QHeaderID :string;
  QuoteDate :string;
  QProduct :string;
  ClientID :string;
  QFirstName :string;
  QLastName :string;
  QMidName :string;
  QDob :string;
  QGender :string;
  QNri :string;
  QEmail :string;
  QMobile :string;
  QOccGroup :string;
  QOccSect :string;
  QOccupation :string;
  QAnnualIncome :string;
  QDeclaration :string;
  AddressID :string;
  QDate :string;
  QCoverage :string;
  QRiskSeqNo :string;
  QAge :string;
  QEmrRating :string;
  QSumAssured :string;
  QRiskCessAge :string;
  QRiskCessTerm :string;
  QRiskCessDate :string;
  QPremCessAge :string;
  QPremCessTerm :string;
  QPremCessDate :string;
  QBeneCessAge :string;
  QBeneCessTerm :string;
  QBeneCessDate :string;
  QAnnualPremium :string;
  QHlyPrem :string;
  QQlyPrem :string;
  QMlyPrem :string;
  QDetailID :string;
  QPolicyYear :string;
  QLifeAssuredAge :string;
  QPolAnnivDate :string;
  QTotalPremPaid :string;
  QRevBonusAmt :string;
  QTerBonusAmt :string;
  QAntiSurBenAmt :string;
  QGuarAdditions :string;
  QLoyaltyAdditions :string;
  QDeathBenefitAmt :string;
  QGuarSurrValue :string;
  QSplSurrValue :string;
  QBonusSurValue :string;
  QAccuDividend :string;
  QAccuDivInterest :string;
  QallocatedAmt :string;
  QUnallocedAmt :string;
  QPesValamt :string;
  QNorValamt :string;
  QOptValamt :string;
  QMaturityDate :string;
  QMaturityAmt :string;
// *** Attention: Check the lookup table open below ***
  qHeadersOpen: boolean;
  clientOpen: boolean;
  qDetailsOpen: boolean;
  addOpen: boolean;
  editOpen: boolean;
  infoOpen: boolean;
  searchString: string;
  searchCriteria: string;
  sortColumn: string;
  sortAsc: boolean;
  sortDesc: boolean;
};

export type ActionConstantsType = {
  ONCHANGE: string;
  EDITCHANGE: string;
  ADDOPEN: string;
  EDITOPEN: string;
  INFOOPEN: string;
  ADDCLOSE: string;
  EDITCLOSE: string;
  INFOCLOSE: string;
  SORT_ASC: string;
  SORT_DESC: string;
  // *** Attention: Check the Lookup table Open/close below ***
  QHEADERSOPEN: string;
  QHEADERSCLOSE: string;
  CLIENTOPEN: string;
  CLIENTCLOSE: string;
  QDETAILSOPEN: string;
  QDETAILSCLOSE: string;
};
export type QuotationModalType = {
  state: QuotationStateType;
  record: any;
  dispatch: React.Dispatch<any>;
  handleFormSubmit: () => Promise<void>;
  ACTIONS: ActionConstantsType;
};
