export type PolicyStateType = {
  CompanyID: string;
  PRCD: string;
  PProduct: string;
  PFreq: string;
  PContractCurr: string;
  PBillCurr: string;
  POffice: string;
  PolStatus: string;
  PReceivedDate: string;
  PUWDate: string;
  ClientID: string;
  PayingAuthority: string;
  AgencyID: string;
  AddressID: string;
  BankID: string;
  BTDate: string;
  PaidToDate: string;
  NxtBTDate: string;
  AnnivDate: string;
  InstalmentPrem: string;
  BillingType: string;
  addOpen: boolean;
  editOpen: boolean;
  infoOpen: boolean;
  clientOpen: boolean;
  authOpen: boolean;
  addressOpen: boolean;
  bankOpen: boolean;
  agencyOpen: boolean;
  benefitOpen: boolean;
  nomineeOpen: boolean;
  benefitClientOpen: boolean;
  searchString: string;
  searchCriteria: string;
  sortColumn: string;
  sortAsc: boolean;
  sortDesc: boolean;
};

export type ActionConstantsType = {
  ONCHANGE: string;
  EDITCHANGE: string;
  ADDOPEN: string;
  EDITOPEN: string;
  INFOOPEN: string;
  ADDCLOSE: string;
  EDITCLOSE: string;
  INFOCLOSE: string;
  CLIENTOPEN: string;
  CLIENTCLOSE: string;
  AUTHOPEN: string;
  AUTHCLOSE: string;
  ADDRESSOPEN: string;
  ADDRESSCLOSE: string;
  BANKOPEN: string;
  BANKCLOSE: string;
  AGENCYOPEN: string;
  AGENCYCLOSE: string;
  BENEFITOPEN: string;
  BENEFITCLOSE: string;
  NOMINEEOPEN: string;
  NOMINEECLOSE: string;
  SORT_ASC: string;
  SORT_DESC: string;
};

export type PolicyModalType = {
  state: PolicyStateType;
  record: any;
  dispatch: React.Dispatch<any>;
  handleFormSubmit: () => any;
  ACTIONS: ActionConstantsType;
};
