export type BenefitStateType = {
  CompanyID: string;
  ClientID: string;
  PolicyID: string;
  BStartDate: string;
  BRiskCessDate: string;
  BPremCessDate: string;
  BTerm: string;
  BPTerm: string;
  BRiskCessAge: string;
  BPremCessAge: string;
  BBasAnnualPrem: string;
  BLoadPrem: string;
  BCoverage: string;
  BSumAssured: string;
  BPrem: string;
  BGender: string;
  BDOB: string;
  BMortality: string;
  BStatus: string;
  BAge: string;
  BRerate: string;
  Interest: string;
  addOpen: boolean;
  editOpen: boolean;
  infoOpen: boolean;
  clientOpen: boolean;
  addressOpen: boolean;
  agencyOpen: boolean;
  benefitOpen: boolean;
  extraOpen: boolean;
  searchString: string;
  searchCriteria: string;
  sortColumn: string;
  sortAsc: boolean;
  sortDesc: boolean;
};

export type ActionConstantsType = {
  ONCHANGE: string;
  EDITCHANGE: string;
  ADDOPEN: string;
  EDITOPEN: string;
  INFOOPEN: string;
  ADDCLOSE: string;
  EDITCLOSE: string;
  INFOCLOSE: string;
  CLIENTOPEN: string;
  CLIENTCLOSE: string;
  ADDRESSOPEN: string;
  ADDRESSCLOSE: string;
  AGENCYOPEN: string;
  AGENCYCLOSE: string;
  BENEFITOPEN: string;
  BENEFITCLOSE: string;
  SORT_ASC: string;
  SORT_DESC: string;
};

export type BenefitModalType = {
  state: BenefitStateType;
  policyRecord: any;
  record: any;
  dispatch: React.Dispatch<any>;
  handleFormSubmit: () => Promise<void>;
  ACTIONS: ActionConstantsType;
  interest: number;
};
