//Attention: Check the path below and change it if required

import { QuotationStateType } from "../../types/quotations/quotationTypes";

//Storing Actions into a Variable for Reducer
export const ACTIONS = {
  ONCHANGE: "ONCHANGE",
  EDITCHANGE: "EDITCHANGE",
  ADDOPEN: "ADDOPEN",
  EDITOPEN: "EDITOPEN",
  INFOOPEN: "INFOOPEN",
  ADDCLOSE: "ADDCLOSE",
  EDITCLOSE: "EDITCLOSE",
  INFOCLOSE: "INFOCLOSE",
  SORT_ASC: "SORT_ASC",
  SORT_DESC: "SORT_DESC",
  // *** Attention: Check the Lookup Open /close ***
  QHEADERSOPEN: "QHEADERSOPEN",
  QHEADERSCLOSE: "QHEADERSCLOSE",
  CLIENTOPEN: "CLIENTOPEN",
  CLIENTCLOSE: "CLIENTCLOSE",
  QDETAILSOPEN: "QDETAILSOPEN",
  QDETAILSCLOSE: "QDETAILSCLOSE",
};

//Initial State defined

export const initialValues: QuotationStateType = {
  CompanyID: "",
  QHeaderID: "",
  QuoteDate: "",
  QProduct: "",
  ClientID: "",
  QFirstName: "",
  QLastName: "",
  QMidName: "",
  QDob: "",
  QGender: "",
  QNri: "",
  QEmail: "",
  QMobile: "",
  QOccGroup: "",
  QOccSect: "",
  QOccupation: "",
  QAnnualIncome: "",
  QDeclaration: "",
  AddressID: "",
  QDate: "",
  QCoverage: "",
  QRiskSeqNo: "",
  QAge: "",
  QEmrRating: "",
  QSumAssured: "",
  QRiskCessAge: "",
  QRiskCessTerm: "",
  QRiskCessDate: "",
  QPremCessAge: "",
  QPremCessTerm: "",
  QPremCessDate: "",
  QBeneCessAge: "",
  QBeneCessTerm: "",
  QBeneCessDate: "",
  QAnnualPremium: "",
  QHlyPrem: "",
  QQlyPrem: "",
  QMlyPrem: "",
  QDetailID: "",
  QPolicyYear: "",
  QLifeAssuredAge: "",
  QPolAnnivDate: "",
  QTotalPremPaid: "",
  QRevBonusAmt: "",
  QTerBonusAmt: "",
  QAntiSurBenAmt: "",
  QGuarAdditions: "",
  QLoyaltyAdditions: "",
  QDeathBenefitAmt: "",
  QGuarSurrValue: "",
  QSplSurrValue: "",
  QBonusSurValue: "",
  QAccuDividend: "",
  QAccuDivInterest: "",
  QallocatedAmt: "",
  QUnallocedAmt: "",
  QPesValamt: "",
  QNorValamt: "",
  QOptValamt: "",
  QMaturityDate: "",
  QMaturityAmt: "",
  addOpen: false,
  editOpen: false,
  infoOpen: false,
  searchString: "",
  searchCriteria: "",
  sortColumn: "",
  sortAsc: false,
  sortDesc: false,
  // *** Attention: Check initial value below ***
  qHeadersOpen: false,
  clientOpen: false,
  qDetailsOpen: false,
};

//Columns Defined to Pass into the Custom Table

export const columns = [
  {
    field: "QHeaderID",
    header: "Header ID",
    dbField: "q_header_id",
  },
  {
    field: "QuoteDate",
    header: "Quote Date",
    dbField: "quote_date",
    type: "date",
  },
  {
    field: "QProduct",
    header: "Product Code",
    dbField: "q_product",
  },
  {
    field: "ClientID",
    header: "Client ID",
    dbField: "client_id",
  },
  {
    field: "QFirstName",
    header: "First Name",
    dbField: "q_first_name",
  },
  {
    field: "QLastName",
    header: "Last Name",
    dbField: "q_last_name",
  },
  {
    field: "QEmail",
    header: "eMail",
    dbField: "q_email",
  },
  {
    field: "QMobile",
    header: "Mobile No",
    dbField: "q_mobile",
  },
];
